### PR TITLE
Allow deselecting selected option

### PR DESCRIPTION
**Pull request by tsujigiri**
[Trello](https://trello.com/c/YGLXgeJ1/753-bug-cannot-remove-a-co-team-lead)

### CODE REVIEW

**Comment by hammerhead** [comment]
Do we maybe want to make this behavior configurable? I guess we have cases where selecting an option is mandatory and we don't want the user to select a blank value.

**Comment by tsujigiri** [comment]
I was originially thinking to tie this to the `required` option, but since we always hardcoded this options where we used chosen, I went for the simple option. I agree, though, that it makes sense to do it.

**Comment by tsujigiri** [comment]
Updated it, so deselect works only for select fields that are not `required`.

**Comment by ndreynolds** [comment]
:thumbsup: LGTM

**Pull request merged**
