### PR TITLE
float-thead does not exist, point to float-thead-slim instead

### PR DESCRIPTION
**Pull request by matthewcorreia-hitfox**

### CODE REVIEW

**Comment by RKushnir** [comment]
Strange. The page says both exist http://mkoryak.github.io/floatThead/, but "if your project includes underscore and you want to save a few bytes you can use the slim version".

**Comment by tsujigiri** [comment]
Since we use underscore anyway... :+1:

**Comment by tsujigiri** [comment]
I added a _temporary solution_ for the bundle issue... :see_no_evil:

**Comment by RKushnir** [comment]
Maybe, you could do something with the `ENV['BUNDLE_GEMFILE']`.

**Comment by dziemba** [comment]
Why not just invoke the Thor task directly, like we discussed?

**Comment by tsujigiri** [comment]
I still need to check if everything is being generated as expected, which is much more convenient in the test.

So, if you guys have better ideas, you are welcome to **try them out**. I'll consider this a good enough solution and not spend any more time on this. :stuck_out_tongue:

**Comment by tsujigiri** [comment]
I removed the _temporary solution_ and added a real one instead.

**Comment by dziemba** [comment]
:mushroom:

**Pull request merged**
