### PR TITLE
Modal component

### PR DESCRIPTION
**Pull request by tsujigiri**
Adds a modal component and tests it using the examples on the styleguide page. I propose we make this the default way we integration-test components, which should ensure that the examples always work.

### CODE REVIEW

**Comment by dziemba** [comment]
I like the idea of using the styleguide for integration tests. But I think we should have it display only the tested compontent in the integration tests, because:
- Other components might affect the tests (e.g. also have elements with the same content etc.)
- Rendering all components in each test will lead to O(n^2) rendering time with n components. That's probably not what we want.

**Comment by tsujigiri** [comment]
In the test I focus on a single instance of the component (using `within`). Also, one could argue, that we also implicitly test that the components don't interfere with each other. I also see that rendering time is an issue, though. I was also thinking, maybe we could organize loading only the assets from the component's directory for its test to make sure, each of them takes care of it's own dependencies (e.g. `require` statements in the JS).

**Comment by tsujigiri** [comment]
How is [this](https://github.com/ad2games/ui_components/commit/917ffd626436690559fe3be52d45e6af42ce4f2f?w=1) instead?

**Comment by tsujigiri** [comment]
Merged via #23.

**Pull request closed without merging**
